name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.15.1'

    - name: Install dependencies
      run: npm ci  # package.json과 package-lock.json을 기반으로 종속성 설치

    - name: Grant execution permissions to PostCSS
      run: chmod +x ./node_modules/.bin/postcss

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.127.0'
        extended: true

    - name: List image files for debugging
      run: |
        echo "Listing image files in /Resources:"
        find . -type f -name "edit_environment_variables.png"
        echo "Listing image files in /content/Resources:"
        find ./content -type f -name "edit_environment_variables.png"
        echo "Listing image files in /static/Resources:"
        find ./static -type f -name "edit_environment_variables.png"

    - name: Build
      run: hugo --minify --gc

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
